# Generated by Django 3.2.5 on 2022-08-05 04:21

import api.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(default='4111111111111111', max_length=17)),
                ('last_4', models.CharField(max_length=4)),
                ('brand', models.CharField(choices=[('amex', 'Amex'), ('discover', 'Discover'), ('mastercard', 'Mastercard'), ('visa', 'Visa')], max_length=255)),
                ('exp_month', models.PositiveSmallIntegerField(validators=[api.models.validateMonth])),
                ('exp_year', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('status', models.CharField(choices=[('draft', 'draft'), ('failed', 'failed'), ('succeeded', 'succeeded')], default='draft', max_length=10)),
                ('success_date', models.DateTimeField(blank=True, null=True, verbose_name='Date when an order was successfully charged')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('requires_confirmation', 'requires_confirmation'), ('succeeded', 'succeeded'), ('failed', 'failed')], default='requires_confirmation', max_length=24)),
                ('success_date', models.DateTimeField(blank=True, null=True, verbose_name='Date when a payment was successfully charged')),
                ('last_processing_error', models.TextField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.order')),
                ('payment_method', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.creditcard')),
            ],
        ),
    ]
