# Generated by Django 3.2.15 on 2023-08-26 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('api', '0004_auto_20230826_0922'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('ebt_card', 'EBT Card')], default='credit_card', max_length=25),
        ),
        migrations.AddField(
            model_name='payment',
            name='target_id',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
    ]
