# Generated by Django 3.2.15 on 2023-08-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20230826_0946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='payment_method',
            new_name='payment_method_types',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_option',
            field=models.CharField(choices=[('credit_card', 'credit_card'), ('ebt_card', 'ebt_card')], default='credit_card', max_length=25),
        ),
        migrations.AlterField(
            model_name='payment',
            name='target_id',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
