# Generated by Django 3.2.15 on 2023-08-26 10:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20230826_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ebt_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
