# Generated by Django 3.2.15 on 2023-08-26 17:01

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_order_ebt_total'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='order',
            constraint=models.CheckConstraint(check=models.Q(('ebt_total__lte', django.db.models.expressions.F('order_total'))), name='ebt_totsl_check'),
        ),
    ]
