# Generated by Django 3.2.15 on 2023-08-26 17:33

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_order_ebt_totsl_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ebtcard',
            name='brand',
            field=models.CharField(choices=[('amex', 'Amex'), ('discover', 'Discover'), ('mastercard', 'Mastercard'), ('visa', 'Visa')], max_length=255),
        ),
        migrations.AlterField(
            model_name='ebtcard',
            name='number',
            field=models.CharField(default='4111111111111112', max_length=19, validators=[api.models.MinLengthValidator]),
        ),
    ]
